run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-use-default: false
  max-same-issues: 3
  exclude-dirs:
    - vendor
    - third_party
  exclude:
    - "generated"
  fix: false

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    checks: ["all"]
  misspell:
    locale: US
  errcheck:
    check-type-assertions: true
    check-blank: true
  goimports:
    local-prefixes: git.quinnzipse.dev/cta-go-sdk

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - prealloc
    - staticcheck
    - unconvert
    - unused
  disable:
    - tenv
